# Generated by Django 3.2.7 on 2021-09-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('make', models.CharField(blank=True, max_length=100)),
                ('plate', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
                ('driver_1', models.CharField(blank=True, max_length=100)),
                ('driver_2', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('VIN_number', models.CharField(blank=True, max_length=100)),
                ('terminal', models.CharField(blank=True, max_length=100)),
                ('city_truck', models.CharField(blank=True, choices=[('BOTH', 'Both'), ('CITY', 'City'), ('HGHWY', 'Highway Truck')], default=None, max_length=5)),
                ('tour', models.IntegerField()),
                ('still_working', models.BooleanField(default=False)),
                ('leave_date', models.DateField()),
                ('truck_ownership', models.CharField(blank=True, choices=[('CMPNY_TRK', 'Company Truck'), ('ONR_OPRTR_PD_ML', 'Owner Operators Paid By Mile'), ('PD_BY_PRCNTG', 'Paid By Percentage')], default=None, max_length=15)),
                ('value', models.FloatField()),
                ('weight_pounds', models.FloatField()),
                ('IFTA_group', models.IntegerField()),
                ('account', models.CharField(blank=True, max_length=100)),
                ('percentage', models.FloatField()),
                ('rate_per_mile_LOAD', models.FloatField()),
                ('rate_per_mile_EMPTY', models.FloatField()),
                ('rate_per_hour', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TruckSafetyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_details', models.CharField(blank=True, max_length=100)),
                ('renewal_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('stop_dispatch_on_expiry', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckMonthlyDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_deductions', models.CharField(blank=True, max_length=100)),
                ('day_of_month', models.IntegerField()),
                ('currency_CDN', models.BooleanField(default=False)),
                ('charges', models.FloatField()),
                ('valid_till', models.DateField()),
                ('belongs_to_company', models.BooleanField(default=False)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('HST', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
        ),
    ]
