# Generated by Django 3.2.7 on 2021-09-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_alter_truck_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='IFTA_group',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truck',
            name='VIN_number',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='account',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver_1',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver_2',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='percentage',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plate',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='rate_per_hour',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truck',
            name='rate_per_mile_EMPTY',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truck',
            name='rate_per_mile_LOAD',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truck',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='terminal',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='tour',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='value',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truck',
            name='weight_pounds',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
