# Generated by Django 3.2.7 on 2021-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
        ('trailers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='truck',
            field=models.ManyToManyField(to='trucks.Truck'),
        ),
    ]
